apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-worker
  template:
    metadata:
      labels:
        app: email-worker
    spec:
      containers:
      - name: email-worker
        image: email-worker-image
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: SMTP_HOST
          value: mail.smtpbucket.com
        - name: SMTP_PORT
          value: "8025"
        command: ["node", "worker.js"]
